name: 'CI'

'on':
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  base-qa:
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v6'

      - uses: 'actions/local/qa-forgejo-folder@v1'

      - uses: 'actions/local/setup-php@v1'
        with:
          php-version: '8.3'

      - name: 'Validate composer.json'
        run: 'composer validate'

      - name: 'Install PHP dependencies'
        run: 'composer update --prefer-dist --no-progress'

      - name: 'Coding Guideline'
        run: './vendor/bin/php-cs-fixer fix --dry-run --diff'

      - name: 'Lint PHPUnit configuration file'
        uses: 'actions/local/qa-xmllint@v1'
        with:
          schema: 'vendor/phpunit/phpunit/phpunit.xsd'
          file: 'phpunit.xml.dist'

  advances-qa:
    runs-on: 'self-hosted'
    needs:
      - 'base-qa'
    strategy:
      matrix:
        include:
          - php-version: '8.2'
            typo3-version: '^13.0'
          - php-version: '8.3'
            typo3-version: '^13.0'
          - php-version: '8.4'
            typo3-version: '^13.0'
          - php-version: '8.5'
            typo3-version: '^13.0'
          - php-version: '8.2'
            typo3-version: '^14.0'
          - php-version: '8.3'
            typo3-version: '^14.0'
          - php-version: '8.4'
            typo3-version: '^14.0'
          - php-version: '8.5'
            typo3-version: '^14.0'
    steps:
      - uses: 'actions/checkout@v6'

      - uses: 'actions/local/setup-php@v1'
        with:
          php-version: '${{ matrix.php-version }}'
          php-extensions: 'sqlite3'

      - name: 'PHP lint'
        run: "find .*.php Classes Tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

      - name: 'Install dependencies with expected TYPO3 version'
        run: 'composer require --prefer-dist --no-progress "typo3/cms-core:${{ matrix.typo3-version }}"'

      - name: 'Code Quality (by PHPStan)'
        run: './vendor/bin/phpstan analyse'

      - name: 'PHPUnit Tests'
        run: './vendor/bin/phpunit --testdox'
